name: Deploy Backend

on:
  push:
    branches: [ main, master ]
    paths: [ 'backend/**' ]
  pull_request:
    branches: [ main, master ]
    paths: [ 'backend/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      run: |
        cd backend
        npm ci

    - name: Run health check
      run: |
        cd backend
        npm start &
        sleep 10
        curl -f http://localhost:5000/api/health || exit 1

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      run: |
        cd backend
        npm ci --only=production

    # Deploy to Vercel
    - name: Deploy to Vercel
      if: github.event_name == 'push'
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./backend
        vercel-args: '--prod'

    # Alternative: Deploy to Heroku
    # - name: Deploy to Heroku
    #   if: github.event_name == 'push'
    #   uses: akhileshns/heroku-deploy@v3.12.12
    #   with:
    #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    #     heroku_app_name: "your-app-name"
    #     heroku_email: "your-email@example.com"
    #     appdir: "backend"

    # Alternative: Deploy to Railway
    # - name: Deploy to Railway
    #   if: github.event_name == 'push'
    #   uses: railwayapp/railway-deploy@v1.1.0
    #   with:
    #     railway-token: ${{ secrets.RAILWAY_TOKEN }}
    #     service: "backend"

  docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/tech24-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/tech24-backend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
